#pragma once

#define FASTFETCH_PROJECT_NAME "fastfetch"
#define FASTFETCH_PROJECT_VERSION "2.67.0"
#define FASTFETCH_PROJECT_VERSION_MAJOR 2
#define FASTFETCH_PROJECT_VERSION_MINOR 67
#define FASTFETCH_PROJECT_VERSION_PATCH 0
#define FASTFETCH_PROJECT_VERSION_GIT "56da8f811068289f6352db8881418aa6e0f994e8"
#define FASTFETCH_PROJECT_VERSION_TWEAK ""
#define FASTFETCH_PROJECT_VERSION_TWEAK_NUM 0
#define FASTFETCH_PROJECT_CMAKE_BUILD_TYPE "LeonOS"
#define FASTFETCH_PROJECT_HOMEPAGE_URL "https://github.com/fastfetch-cli/fastfetch"
#define FASTFETCH_PROJECT_DESCRIPTION "Fast neofetch-like system information tool"
#define FASTFETCH_PROJECT_LICENSE "MIT license"

#define FASTFETCH_TARGET_DIR_ROOT "0:/"
#define FASTFETCH_TARGET_DIR_USR "0:/"
#define FASTFETCH_TARGET_DIR_HOME "0:/users"
#define FASTFETCH_TARGET_DIR_ETC "0:/system/config"
#define FASTFETCH_TARGET_DIR_INSTALL_SYSCONF "0:/system/config"
