#ifndef LEONOS_UAPI_LINUX_SYSCALL_H
#define LEONOS_UAPI_LINUX_SYSCALL_H

/* x86_64 Linux syscall numbers supported or reserved by LeonOS. */
#define __NR_read              0
#define __NR_write             1
#define __NR_open               2
#define __NR_close              3
#define __NR_stat               4
#define __NR_fstat              5
#define __NR_lseek              8
#define __NR_ftruncate         77
#define __NR_mmap               9
#define __NR_mprotect          10
#define __NR_munmap            11
#define __NR_ioctl             16
#define __NR_poll              7
#define __NR_sched_yield       24
#define __NR_mremap            25
#define __NR_madvise           28
#define __NR_nanosleep         35
#define __NR_getpid            39
#define __NR_socket            41
#define __NR_connect           42
#define __NR_accept            43
#define __NR_socketpair         53
#define __NR_accept4           288
#define __NR_sendto            44
#define __NR_recvfrom          45
#define __NR_sendmsg           46
#define __NR_recvmsg           47
#define __NR_shutdown          48
#define __NR_bind              49
#define __NR_listen            50
#define __NR_getsockname       51
#define __NR_getpeername       52
#define __NR_getsockopt        55
#define __NR_setsockopt        54
#define __NR_clone             56
#define __NR_fork              57
#define __NR_vfork             58
#define __NR_execve            59
#define __NR_exit              60
#define __NR_wait4             61
#define __NR_kill              62
#define __NR_brk               12
#define __NR_dup               32
#define __NR_dup2              33
#define __NR_fcntl             72
#define __NR_getcwd            79
#define __NR_chdir             80
#define __NR_rename            82
#define __NR_mkdir             83
#define __NR_rmdir             84
#define __NR_unlink            87
#define __NR_openat            257
#define __NR_readlink          89
#define __NR_clock_gettime     228
#define __NR_rt_sigaction      13
#define __NR_rt_sigprocmask    14
#define __NR_rt_sigreturn      15
#define __NR_rt_sigsuspend     130
#define __NR_mount             165
#define __NR_umount2           166
#define __NR_getppid           110
#define __NR_getuid             102
#define __NR_getgid             104
#define __NR_geteuid            107
#define __NR_getegid            108
#define __NR_setuid             105
#define __NR_setgid             106
#define __NR_uname              63
#define __NR_gettimeofday        96
#define __NR_settimeofday       164
#define __NR_chmod              90
#define __NR_fchmod             91
#define __NR_chown              92
#define __NR_fchown             93
#define __NR_sched_setaffinity  203
#define __NR_sched_getaffinity  204
#define __NR_reboot             169
#define __NR_pipe2              293
#define __NR_dup3               292
#define __NR_getpgrp           111
#define __NR_setsid            112
#define __NR_getpgid           121
#define __NR_setpgid           109
#define __NR_getpriority       140
#define __NR_setpriority       141
#define __NR_getrlimit         97
#define __NR_setrlimit         160
#define __NR_pipe               22

#define __NR_send               44
#define __NR_recv               45

/* Common aliases used by Linux headers. */
#define SYS_read __NR_read
#define SYS_write __NR_write
#define SYS_open __NR_open
#define SYS_close __NR_close
#define SYS_stat __NR_stat
#define SYS_fstat __NR_fstat
#define SYS_lseek __NR_lseek
#define SYS_ftruncate __NR_ftruncate
#define SYS_mmap __NR_mmap
#define SYS_mprotect __NR_mprotect
#define SYS_munmap __NR_munmap
#define SYS_ioctl __NR_ioctl
#define SYS_poll __NR_poll
#define SYS_sched_yield __NR_sched_yield
#define SYS_nanosleep __NR_nanosleep
#define SYS_getpid __NR_getpid
#define SYS_send __NR_send
#define SYS_recv __NR_recv
#define SYS_socket __NR_socket
#define SYS_connect __NR_connect
#define SYS_accept __NR_accept
#define SYS_sendto __NR_sendto
#define SYS_recvfrom __NR_recvfrom
#define SYS_shutdown __NR_shutdown
#define SYS_bind __NR_bind
#define SYS_listen __NR_listen
#define SYS_getsockname __NR_getsockname
#define SYS_getsockopt __NR_getsockopt
#define SYS_setsockopt __NR_setsockopt
#define SYS_dup __NR_dup
#define SYS_dup2 __NR_dup2
#define SYS_fcntl __NR_fcntl
#define SYS_fork __NR_fork
#define SYS_vfork __NR_vfork
#define SYS_execve __NR_execve
#define SYS_exit __NR_exit
#define SYS_wait4 __NR_wait4
#define SYS_kill __NR_kill
#define SYS_getcwd __NR_getcwd
#define SYS_chdir __NR_chdir
#define SYS_rename __NR_rename
#define SYS_mkdir __NR_mkdir
#define SYS_rmdir __NR_rmdir
#define SYS_unlink __NR_unlink
#define SYS_openat __NR_openat
#define SYS_readlink __NR_readlink
#define SYS_clock_gettime __NR_clock_gettime
#define SYS_rt_sigaction __NR_rt_sigaction
#define SYS_rt_sigprocmask __NR_rt_sigprocmask
#define SYS_rt_sigreturn __NR_rt_sigreturn
#define SYS_rt_sigsuspend __NR_rt_sigsuspend
#define SYS_brk __NR_brk
#define SYS_pipe __NR_pipe
#define SYS_pipe2 __NR_pipe2
#define SYS_dup3 __NR_dup3
#define SYS_socketpair __NR_socketpair
#define SYS_sendmsg __NR_sendmsg
#define SYS_recvmsg __NR_recvmsg
#define SYS_accept4 __NR_accept4
#define SYS_getuid __NR_getuid
#define SYS_getgid __NR_getgid
#define SYS_geteuid __NR_geteuid
#define SYS_getegid __NR_getegid
#define SYS_setuid __NR_setuid
#define SYS_setgid __NR_setgid
#define SYS_uname __NR_uname
#define SYS_gettimeofday __NR_gettimeofday
#define SYS_settimeofday __NR_settimeofday
#define SYS_chmod __NR_chmod
#define SYS_fchmod __NR_fchmod
#define SYS_chown __NR_chown
#define SYS_fchown __NR_fchown
#define SYS_sched_setaffinity __NR_sched_setaffinity
#define SYS_sched_getaffinity __NR_sched_getaffinity
#define SYS_reboot __NR_reboot
#define SYS_mount __NR_mount
#define SYS_umount2 __NR_umount2

#endif
