CONFIG_VMDK_DEFAULT_LANGUAGE_EN=y
# CONFIG_VMDK_DEFAULT_LANGUAGE_ZH is not set
CONFIG_VMDK_REQUIRE_LICENSE=y
CONFIG_INSTALLER_INSTALLED_REQUIRE_LICENSE=y
CONFIG_IMAGE_SIZE_MIB=192
CONFIG_INSTALLER_ROOT_SIZE_MIB=128
CONFIG_VMDK_DEFAULT_THEME_METRO=y
# CONFIG_VMDK_DEFAULT_THEME_WIN95 is not set
CONFIG_VMDK_WALLPAPER_FILL=y
# CONFIG_VMDK_WALLPAPER_STRETCH is not set
# CONFIG_VMDK_WALLPAPER_CENTER is not set
# CONFIG_BUILD_PRESET_DEBUG is not set
CONFIG_BUILD_PRESET_DEVELOP=y
# CONFIG_BUILD_PRESET_RELEASE is not set
CONFIG_BUILD_USE_ADVANCED_OVERRIDES=n
CONFIG_BUILD_OPTIMIZATION_LEVEL=2
CONFIG_BUILD_DEBUG_SYMBOLS=y
# CONFIG_BUILD_ENABLE_LTO is not set
# CONFIG_BUILD_STRIP_BINARIES is not set
# CONFIG_BUILD_DEVELOPER_DIAGNOSTICS is not set
# CONFIG_BUILD_VERBOSE_LOG is not set
CONFIG_QEMU_MEMORY_MB=512
CONFIG_QEMU_DISPLAY_WIDTH=1920
CONFIG_QEMU_DISPLAY_HEIGHT=1080
CONFIG_QEMU_ENABLE_KVM=y
CONFIG_QEMU_NET_DEVICE="e1000"
CONFIG_QEMU_OVMF_PATH="/usr/share/ovmf/OVMF.fd"
CONFIG_LICENSE_SERVER_URL="http://127.0.0.1:30301"
CONFIG_LICENSE_DEBUG_LOG=y
CONFIG_TEST_LICENSE_SERVER=y
CONFIG_TEST_LOS2W=y
CONFIG_TEST_QMP_TERMINAL=y
CONFIG_TEST_QMP_TCC=y
CONFIG_TEST_QMP_STARDUST=y
CONFIG_TEST_COMPONENT_CONFIG=y
CONFIG_SDK_INCLUDE_COMPONENT_METADATA=y
CONFIG_RELEASE_WRITE_CHECKSUMS=y
CONFIG_RELEASE_INCLUDE_THIRD_PARTY_NOTICES=y
