CONFIG_VMDK_REQUIRE_LICENSE=y
CONFIG_INSTALLER_INSTALLED_REQUIRE_LICENSE=y
CONFIG_IMAGE_SIZE_MIB=192
CONFIG_INSTALLER_ROOT_SIZE_MIB=128
CONFIG_QEMU_MEMORY_MB=512
CONFIG_QEMU_DISPLAY_WIDTH=1920
CONFIG_QEMU_DISPLAY_HEIGHT=1080
CONFIG_QEMU_ENABLE_KVM=y
CONFIG_QEMU_NET_DEVICE="e1000"
CONFIG_QEMU_OVMF_PATH="/usr/share/ovmf/OVMF.fd"
CONFIG_LICENSE_SERVER_URL="http://127.0.0.1:30301"
CONFIG_LICENSE_DEBUG_LOG=y
