"""LeonOS ABI constants used by los2w."""

USER_BASE = 0x0000000000400000
USER_TOP = 0x0000000004000000
USER_MMAP_BASE = 0x0000000002000000
USER_STACK_TOP = USER_TOP - 0x1000
USER_STACK_PAGES = 16
PAGE_SIZE = 0x1000

SYS_READ = 0
SYS_WRITE = 1
SYS_OPEN = 2
SYS_CLOSE = 3
SYS_STAT = 4
SYS_FSTAT = 5
SYS_LSEEK = 8
SYS_MMAP = 9
SYS_MUNMAP = 11
SYS_IOCTL = 16
SYS_SCHED_YIELD = 24
SYS_NANOSLEEP = 35
SYS_GETPID = 39
SYS_EXECVE = 59
SYS_EXIT = 60
SYS_WAIT4 = 61
SYS_GETCWD = 79
SYS_CHDIR = 80
SYS_RENAME = 82
SYS_MKDIR = 83
SYS_RMDIR = 84
SYS_UNLINK = 87

SYSCALL_NAMES = {
    SYS_READ: "read",
    SYS_WRITE: "write",
    SYS_OPEN: "open",
    SYS_CLOSE: "close",
    SYS_STAT: "stat",
    SYS_FSTAT: "fstat",
    SYS_LSEEK: "lseek",
    SYS_MMAP: "mmap",
    SYS_MUNMAP: "munmap",
    SYS_IOCTL: "ioctl",
    SYS_SCHED_YIELD: "sched_yield",
    SYS_NANOSLEEP: "nanosleep",
    SYS_GETPID: "getpid",
    SYS_EXECVE: "execve",
    SYS_EXIT: "exit",
    SYS_WAIT4: "wait4",
    SYS_GETCWD: "getcwd",
    SYS_CHDIR: "chdir",
    SYS_RENAME: "rename",
    SYS_MKDIR: "mkdir",
    SYS_RMDIR: "rmdir",
    SYS_UNLINK: "unlink",
}

O_RDONLY = 0x0000
O_WRONLY = 0x0001
O_RDWR = 0x0002
O_ACCMODE = 0x0003
O_CREAT = 0x0040
O_TRUNC = 0x0200
O_APPEND = 0x0400

SEEK_SET = 0
SEEK_CUR = 1
SEEK_END = 2

PROT_READ = 0x1
PROT_WRITE = 0x2
PROT_EXEC = 0x4
MAP_PRIVATE = 0x02
MAP_FIXED = 0x10
MAP_ANONYMOUS = 0x20
MAP_FAILED = 0xFFFFFFFFFFFFFFFF

FS_NAME_LEN = 128
FS_PATH_LEN = 256
FS_TYPE_FILE = 1
FS_TYPE_DIR = 2
FS_TYPE_DEVICE = 3
IOCTL_LIST_DIR = 0x4C444952

GUI_IOCTL_VERSION = 0x4C475549
GUI_IOCTL_PATH_TEST = 0x4C504154
GUI_IOCTL_EVENT = 0x4C455654
GUI_IOCTL_UPTIME_MS = 0x4C555054
GUI_IOCTL_FB_INFO = 0x4C464249
GUI_IOCTL_CREATE_WINDOW = 0x4C475743
GUI_IOCTL_POLL_WINDOW = 0x4C475750
GUI_IOCTL_TASKS = 0x4C54534B
GUI_IOCTL_PRESENT_WINDOW = 0x4C475046
GUI_IOCTL_FETCH_WINDOW = 0x4C475746
GUI_IOCTL_WINDOW_EVENT = 0x4C475745
GUI_IOCTL_SEND_WINDOW_EVENT = 0x4C475753
GUI_IOCTL_DESTROY_WINDOW = 0x4C475744
GUI_IOCTL_TASK_KILL = 0x4C544B49
GUI_IOCTL_REBOOT = 0x4C524254
GUI_IOCTL_SHUTDOWN = 0x4C534844
GUI_IOCTL_DISPLAY_STATE = 0x4C445350

APP_EVENT_CLOSE = 1
APP_EVENT_FOCUS = 2
APP_EVENT_BLUR = 3
APP_EVENT_RESIZE = 4
APP_EVENT_MOUSE_MOVE = 5
APP_EVENT_MOUSE_BUTTON = 6
APP_EVENT_KEY_DOWN = 7
APP_EVENT_KEY_UP = 8
APP_EVENT_MOUSE_WHEEL = 9

KEY_ESCAPE = 1
KEY_BACKSPACE = 14
KEY_TAB = 15
KEY_ENTER = 28
KEY_LEFT_CTRL = 29
KEY_LEFT_SHIFT = 42
KEY_RIGHT_SHIFT = 54
KEY_LEFT_ALT = 56
KEY_SPACE = 57
KEY_HOME = 71
KEY_PAGE_UP = 73
KEY_LEFT = 75
KEY_RIGHT = 77
KEY_END = 79
KEY_DOWN = 80
KEY_PAGE_DOWN = 81
KEY_INSERT = 82
KEY_DELETE = 83
KEY_UP = 72
KEY_RIGHT_ALT = 115
KEY_RIGHT_CTRL = 116

AUTH_IOCTL_STATUS = 0x4C415553
AUTH_IOCTL_CURRENT = 0x4C415543
AUTH_ROLE_NONE = 0
AUTH_ROLE_USER = 1
AUTH_ROLE_ADMIN = 2

SYSTEM_IOCTL_INFO = 0x4C535953
PERF_IOCTL_INFO = 0x4C504552
TIME_IOCTL_INFO = 0x4C54494D
TIME_IOCTL_NTP_SYNC = 0x4C544E54
MACHINE_IDENTITY_IOCTL = 0x4C4D4944

TEXT_IOCTL_LAYOUT_UTF8 = 0x4C545854
FONT_W = 8

NET_IOCTL_PING = 0x4C4E5047
NET_IOCTL_CONFIG = 0x4C4E4346
NET_IOCTL_DHCP = 0x4C4E4448
NET_IOCTL_DNS = 0x4C4E444E
NET_IOCTL_HTTP_GET = 0x4C4E4854
NET_IOCTL_SOCKET_OPEN = 0x4C4E534F
NET_IOCTL_SOCKET_CONNECT = 0x4C4E5343
NET_IOCTL_SOCKET_SEND = 0x4C4E5353
NET_IOCTL_SOCKET_RECV = 0x4C4E5352
NET_IOCTL_SOCKET_CLOSE = 0x4C4E5358
NET_IOCTL_CONNECTIONS = 0x4C4E434E

NET_STATUS_OK = 0
NET_STATUS_NO_DEVICE = 1
NET_STATUS_BAD_ARGUMENT = 4
NET_STATUS_DHCP_FAILED = 7
NET_STATUS_DNS_FAILED = 9
NET_STATUS_DNS_NO_ANSWER = 10
NET_STATUS_TCP_TIMEOUT = 11
NET_STATUS_TCP_RESET = 12
NET_STATUS_TCP_FAILED = 13
NET_STATUS_HTTP_FAILED = 14
NET_STATUS_HTTP_TOO_LARGE = 15
NET_STATUS_SOCKET_LIMIT = 16
NET_STATUS_SOCKET_BAD_HANDLE = 17
NET_STATUS_SOCKET_NOT_CONNECTED = 18
NET_STATUS_SOCKET_CLOSED = 19
NET_STATUS_PROTOCOL_UNSUPPORTED = 20

NET_CONFIG_SOURCE_DHCP = 2
NET_CONFIG_FLAG_PRESENT = 0x1
NET_CONFIG_FLAG_ACTIVE = 0x2
NET_CONFIG_FLAG_DHCP = 0x4
NET_HOSTNAME_LEN = 128
NET_DNS_MAX_ADDRESSES = 4
NET_HTTP_PATH_LEN = 256
NET_HTTP_RESPONSE_MAX = 4096
NET_SOCKET_MAX = 16
NET_AF_INET = 2
NET_SOCK_STREAM = 1
NET_IPPROTO_TCP = 6
NET_TCP_CLOSED = 0
NET_TCP_ESTABLISHED = 2

HTTP_CONTENT_TYPE_LEN = 64
HTTP_URL_LEN = FS_PATH_LEN

IOCTL_NAMES = {
    IOCTL_LIST_DIR: "LEONOS_IOCTL_LIST_DIR",
    GUI_IOCTL_VERSION: "LEONOS_GUI_IOCTL_VERSION",
    GUI_IOCTL_PATH_TEST: "LEONOS_GUI_IOCTL_PATH_TEST",
    GUI_IOCTL_EVENT: "LEONOS_GUI_IOCTL_EVENT",
    GUI_IOCTL_UPTIME_MS: "LEONOS_GUI_IOCTL_UPTIME_MS",
    GUI_IOCTL_FB_INFO: "LEONOS_GUI_IOCTL_FB_INFO",
    GUI_IOCTL_CREATE_WINDOW: "LEONOS_GUI_IOCTL_CREATE_WINDOW",
    GUI_IOCTL_POLL_WINDOW: "LEONOS_GUI_IOCTL_POLL_WINDOW",
    GUI_IOCTL_TASKS: "LEONOS_GUI_IOCTL_TASKS",
    GUI_IOCTL_PRESENT_WINDOW: "LEONOS_GUI_IOCTL_PRESENT_WINDOW",
    GUI_IOCTL_FETCH_WINDOW: "LEONOS_GUI_IOCTL_FETCH_WINDOW",
    GUI_IOCTL_WINDOW_EVENT: "LEONOS_GUI_IOCTL_WINDOW_EVENT",
    GUI_IOCTL_SEND_WINDOW_EVENT: "LEONOS_GUI_IOCTL_SEND_WINDOW_EVENT",
    GUI_IOCTL_DESTROY_WINDOW: "LEONOS_GUI_IOCTL_DESTROY_WINDOW",
    AUTH_IOCTL_STATUS: "LEONOS_AUTH_IOCTL_STATUS",
    AUTH_IOCTL_CURRENT: "LEONOS_AUTH_IOCTL_CURRENT",
    SYSTEM_IOCTL_INFO: "LEONOS_IOCTL_SYSTEM_INFO",
    PERF_IOCTL_INFO: "LEONOS_IOCTL_PERF_INFO",
    TIME_IOCTL_INFO: "LEONOS_IOCTL_TIME_INFO",
    TIME_IOCTL_NTP_SYNC: "LEONOS_IOCTL_TIME_NTP_SYNC",
    MACHINE_IDENTITY_IOCTL: "LEONOS_IOCTL_MACHINE_IDENTITY",
    TEXT_IOCTL_LAYOUT_UTF8: "LEONOS_TEXT_IOCTL_LAYOUT_UTF8",
    NET_IOCTL_CONFIG: "LEONOS_IOCTL_NET_CONFIG",
    NET_IOCTL_DHCP: "LEONOS_IOCTL_NET_DHCP",
    NET_IOCTL_DNS: "LEONOS_IOCTL_NET_DNS",
    NET_IOCTL_HTTP_GET: "LEONOS_IOCTL_NET_HTTP_GET",
    NET_IOCTL_SOCKET_OPEN: "LEONOS_IOCTL_NET_SOCKET_OPEN",
    NET_IOCTL_SOCKET_CONNECT: "LEONOS_IOCTL_NET_SOCKET_CONNECT",
    NET_IOCTL_SOCKET_SEND: "LEONOS_IOCTL_NET_SOCKET_SEND",
    NET_IOCTL_SOCKET_RECV: "LEONOS_IOCTL_NET_SOCKET_RECV",
    NET_IOCTL_SOCKET_CLOSE: "LEONOS_IOCTL_NET_SOCKET_CLOSE",
    NET_IOCTL_CONNECTIONS: "LEONOS_IOCTL_NET_CONNECTIONS",
}
