#ifndef LEONOS_SYS_MMAN_H
#define LEONOS_SYS_MMAN_H

#include <leonos/syscall.h>

#define PROT_READ LEONOS_PROT_READ
#define PROT_WRITE LEONOS_PROT_WRITE
#define PROT_EXEC LEONOS_PROT_EXEC

#define MAP_PRIVATE LEONOS_MAP_PRIVATE
#define MAP_FIXED LEONOS_MAP_FIXED
#define MAP_ANONYMOUS LEONOS_MAP_ANONYMOUS
#define MAP_ANON LEONOS_MAP_ANONYMOUS
#define MAP_FAILED LEONOS_MAP_FAILED

int mprotect(void *addr, size_t len, int prot);

#endif
