#!/usr/bin/env python3
"""Build a small static BusyBox for the LeonOS Picolibc userland."""

from __future__ import annotations

import argparse
import hashlib
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
WORK_PREFIX = "leonos4-busybox-"


# BusyBox's upstream libbb/Kbuild.src compiles a broad support library even
# when allnoconfig selects only a few applets.  LeonOS deliberately does not
# expose Linux sockets, ptys, process groups, or fork semantics to this port;
# limit the copied source tree to the helpers used by the small file/text
# profile instead of growing placeholder ABI declarations for unavailable APIs.
MINIMAL_LIBBB_OBJECTS = (
    "appletlib.o",
    "auto_string.o",
    "bb_cat.o",
    "leonos_shim.o",
    "bb_pwd.o",
    "bb_qsort.o",
    "bb_strtonum.o",
    "chomp.o",
    "compare_string_array.o",
    "concat_path_file.o",
    "const_hack.o",
    "copyfd.o",
    "default_error_retval.o",
    "common_bufsiz.o",
    "endofname.o",
    "fflush_stdout_and_exit.o",
    "full_write.o",
    "fclose_nonstdin.o",
    "get_last_path_component.o",
    "get_line_from_file.o",
    "getopt32.o",
    "getopt_allopts.o",
    "human_readable.o",
    "iterate_on_dir.o",
    "last_char_is.o",
    "llist.o",
    "make_directory.o",
    "messages.o",
    "mode_string.o",
    "parse_mode.o",
    "nuke_str.o",
    "perror_msg.o",
    "perror_nomsg.o",
    "perror_nomsg_and_die.o",
    "print_flags.o",
    "print_numbered_lines.o",
    "printable.o",
    "printable_string.o",
    "process_escape_sequence.o",
    "ptr_to_globals.o",
    "read.o",
    "safe_write.o",
    "safe_strncpy.o",
    "single_argv.o",
    "skip_whitespace.o",
    "verror_msg.o",
    "vfork_daemon_rexec.o",
    "xatonum.o",
    "xfunc_die.o",
    "xfuncs.o",
    "xfuncs_printf.o",
    "xgetcwd.o",
    "xreadlink.o",
    "xrealloc_vector.o",
    "wfopen_input.o",
    "wfopen.o",
    "read_key.o",
    "safe_poll.o",
    "read_printf.o",
)

def run(command: list[str], *, cwd: Path | None = None) -> None:
    subprocess.run(command, cwd=cwd, check=True)


def source_revision(source: Path) -> str:
    result = subprocess.run(
        ["git", "-C", str(source), "rev-parse", "HEAD"],
        check=True,
        text=True,
        capture_output=True,
    )
    return result.stdout.strip()


def copy_tree(source: Path, destination: Path) -> None:
    shutil.copytree(source, destination, ignore=shutil.ignore_patterns(".git"))


def archive_members(archive: Path) -> list[str]:
    result = subprocess.run(
        ["llvm-ar", "t", str(archive)], check=True, text=True, capture_output=True
    )
    return [line for line in result.stdout.splitlines() if line]


def merge_static_archives(output: Path, archives: list[Path], work_dir: Path) -> None:
    if work_dir.exists():
        shutil.rmtree(work_dir)
    work_dir.mkdir()
    members: list[Path] = []
    for archive in archives:
        names = archive_members(archive)
        run(["llvm-ar", "x", str(archive)], cwd=work_dir)
        members.extend(work_dir / name for name in names)
    run(["llvm-ar", "rcs", str(output), *map(str, members)])


def source_cache_key(revision: str) -> str:
    digest = hashlib.sha256()
    digest.update(revision.encode("ascii"))
    # The source copy is modified by this script and the LeonOS adapter, so
    # an upstream revision alone cannot identify a reusable copy.
    for path in (Path(__file__), ROOT / "userland/busybox/leonos_shim.c"):
        digest.update(path.read_bytes())
    return digest.hexdigest()


def cached_source(source: Path, cache_key: str) -> Path:
    cache_root = Path(tempfile.gettempdir()) / f"{WORK_PREFIX}{cache_key[:20]}"
    marker = cache_root / ".leonos-source-cache-key"
    existing_key = marker.read_text(encoding="ascii").strip() if marker.is_file() else ""
    if existing_key != cache_key:
        if cache_root.exists():
            shutil.rmtree(cache_root)
        cache_root.mkdir(parents=True)
        copy_tree(source, cache_root / "source")
        marker.write_text(cache_key + "\n", encoding="ascii")
    return cache_root / "source"


def write_minimal_libbb_kbuild(kbuild: Path, generated: bool) -> None:
    body = [
        "# Generated by tools/build_busybox.py for the LeonOS basic applet profile." if generated
        else "# BusyBox source-copy override for the LeonOS basic applet profile.",
        "# The upstream source tree is never modified; this file is in the /tmp copy.",
        "lib-y :=",
        "",
    ]
    body.extend(f"lib-y += {name}" for name in MINIMAL_LIBBB_OBJECTS)
    body.append("")
    kbuild.write_text("\n".join(body), encoding="utf-8")


def trim_libbb(source: Path) -> None:
    shutil.copyfile(ROOT / "userland/busybox/leonos_shim.c", source / "libbb/leonos_shim.c")
    write_minimal_libbb_kbuild(source / "libbb/Kbuild.src", False)
    allowed = {Path(name).stem for name in MINIMAL_LIBBB_OBJECTS}
    for path in (source / "libbb").rglob("*.c"):
        if path.stem in allowed:
            continue
        text = path.read_text(encoding="utf-8")
        # scripts/generate_BUFSIZ.sh and the Kbuild generator discover these
        # annotations from source files and append them after Kbuild.src.
        text = text.replace("//kbuild:", "//leonos-kbuild:")
        path.write_text(text, encoding="utf-8")


def enable_leonos_spawn_fallback(source: Path) -> None:
    path = source / "shell/hush.c"
    text = path.read_text(encoding="utf-8")
    include_marker = '#include "shell_common.h"'
    include_addition = (
        include_marker
        + "\n#include <leonos/pty.h>\n"
          "extern int leonos_spawn_wait_argv(const char *path, char *const argv[]);\n"
          "extern int leonos_spawn_busybox_applet_wait(const char *path, char *const argv[]);"
    )
    if "leonos_spawn_wait_argv" not in text:
        if include_marker not in text:
            raise SystemExit("unable to add LeonOS spawn declaration to hush")
        text = text.replace(include_marker, include_addition, 1)

    marker = " must_fork:\n"
    if "LeonOS has no fork/exec replacement ABI" not in text:
        replacement = """ must_fork:
#if ENABLE_FEATURE_SH_NOFORK
\t/* LeonOS has no fork/exec replacement ABI; spawn one simple command. */
\tif (pi->num_cmds == 1 && pi->followup == PIPE_SEQ && argv_expanded && argv_expanded[0]) {
\t\tchar *spawn_path = NULL;
\t\tint applet_no = strchr(argv_expanded[0], '/') ? -1 : find_applet_by_name(argv_expanded[0]);
\t\t/* The image has one BusyBox executable, not per-applet links. */
\t\tif (applet_no >= 0) {
\t\t\trcode = leonos_spawn_busybox_applet_wait("0:/programs/busybox/busybox.elf", argv_expanded);
\t\t\tfree(argv_expanded);
\t\t\tdebug_leave();
\t\t\treturn rcode;
\t\t}
\t\tif (strchr(argv_expanded[0], '/'))
\t\t\tspawn_path = xstrdup(argv_expanded[0]);
\t\telse
\t\t\tspawn_path = find_in_path(argv_expanded[0]);
\t\tif (!spawn_path) {
\t\t\tbb_error_msg("%s: not found", argv_expanded[0]);
\t\t\tfree(argv_expanded);
\t\t\tdebug_leave();
\t\t\treturn 127;
\t\t}
\t\trcode = leonos_spawn_wait_argv(spawn_path, argv_expanded);
\t\tfree(spawn_path);
\t\tfree(argv_expanded);
\t\tdebug_leave();
\t\treturn rcode;
\t}
#endif

"""
        if text.count(marker) != 1:
            raise SystemExit("unexpected hush must_fork marker count")
        text = text.replace(marker, replacement, 1)

    old_error = 'bb_simple_perror_msg(BB_MMU ? "vfork"+1 : "vfork");'
    if old_error in text:
        text = text.replace(
            old_error,
            'bb_error_msg("process spawning is unavailable for pipelines or background commands");',
            1,
        )
    path.write_text(text, encoding="utf-8")


def read_fragment(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line:
            continue
        if line.startswith("# CONFIG_") and line.endswith(" is not set"):
            values[line[2 : -len(" is not set")]] = "n"
            continue
        if line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        if key.startswith("CONFIG_"):
            values[key] = value
    return values


def apply_fragment(config: Path, values: dict[str, str]) -> None:
    lines = config.read_text(encoding="utf-8").splitlines()
    seen: set[str] = set()
    result: list[str] = []
    for line in lines:
        match = re.match(r"(?:# )?(CONFIG_[A-Za-z0-9_]+)(?:=.*| is not set)$", line)
        if not match or match.group(1) not in values:
            result.append(line)
            continue
        key = match.group(1)
        if key in seen:
            continue
        value = values[key]
        result.append(f"# {key} is not set" if value == "n" else f"{key}={value}")
        seen.add(key)
    for key, value in values.items():
        if key not in seen:
            result.append(f"# {key} is not set" if value == "n" else f"{key}={value}")
    config.write_text("\n".join(result) + "\n", encoding="utf-8")


def clang_resource_headers() -> Path:
    result = subprocess.run(
        ["clang", "-print-resource-dir"], check=True, text=True, capture_output=True
    )
    headers = Path(result.stdout.strip()) / "include"
    if not headers.is_dir():
        raise SystemExit(f"Clang resource headers are missing: {headers}")
    return headers


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--config", type=Path, required=True)
    parser.add_argument("--picolibc-prefix", type=Path, required=True)
    parser.add_argument("--leonos-libc-include", type=Path, required=True)
    parser.add_argument("--leonos-include", type=Path, required=True)
    parser.add_argument("--linker-script", type=Path, required=True)
    parser.add_argument("--leonos-lib", type=Path, required=True)
    parser.add_argument("--picolibc-lib", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--stamp", type=Path, required=True)
    args = parser.parse_args()

    if os.name == "nt":
        raise SystemExit("BusyBox must be built from WSL/Linux, not Windows")
    source = args.source.resolve()
    required = [
        source / "Makefile", args.config, args.picolibc_prefix / "include",
        args.leonos_libc_include, args.leonos_include, args.linker_script,
        args.leonos_lib, args.picolibc_lib, ROOT / "userland/busybox/leonos_shim.c",
    ]
    for path in required:
        if not path.exists():
            raise SystemExit(f"required BusyBox input is missing: {path}")

    revision = source_revision(source)
    source_dir = cached_source(source, source_cache_key(revision))
    trim_libbb(source_dir)
    enable_leonos_spawn_fallback(source_dir)
    work_root = source_dir.parent
    output_dir = work_root / "output"
    sdk_dir = work_root / "sdk"
    lib_dir = work_root / "lib"
    for path in (output_dir, sdk_dir, lib_dir):
        if path.exists():
            shutil.rmtree(path)
    output_dir.mkdir()
    sdk_dir.mkdir()
    lib_dir.mkdir()

    # BusyBox cannot handle the repository's space-containing path in O=.
    copy_tree(args.picolibc_prefix, sdk_dir / "picolibc")
    copy_tree(args.leonos_libc_include, sdk_dir / "leonos-libc")
    copy_tree(args.leonos_include, sdk_dir / "include")
    copy_tree(ROOT / "userland/busybox/include", sdk_dir / "busybox-include")
    linker_script = sdk_dir / "linker.ld"
    shutil.copyfile(args.linker_script, linker_script)
    adapter_lib = lib_dir / "libleonos-adapter.a"
    shutil.copyfile(args.leonos_lib, adapter_lib)
    shutil.copyfile(args.picolibc_lib, lib_dir / "libc.a")
    merge_static_archives(lib_dir / "libleonos.a",
                          [adapter_lib, args.picolibc_lib.resolve()],
                          work_root / "archive-merge")
    # BusyBox's generic link recipe always probes crypt, m, and rt. The
    # selected applets need none of them; keep empty archives so that probe
    # does not accidentally link a second copy of Picolibc (and its syscall
    # fallbacks) through libm.
    for name in ("libcrypt.a", "libm.a", "librt.a"):
        run(["llvm-ar", "rcs", str(lib_dir / name)])

    run(["make", "-C", str(source_dir), f"O={output_dir}", "allnoconfig"])
    generated_config = output_dir / ".config"
    apply_fragment(generated_config, read_fragment(args.config.resolve()))
    run(["make", "-C", str(source_dir), f"O={output_dir}", "oldconfig"], cwd=source_dir)
    # scripts/gen_build_files appends generic Linux-oriented libbb helpers to
    # the generated Kbuild. Replace the generated copy after configuration as
    # well, otherwise those objects override the source-copy profile above.
    write_minimal_libbb_kbuild(output_dir / "libbb/Kbuild", True)

    headers = clang_resource_headers()
    cflags = " ".join([
        "-target", "x86_64-unknown-none", "-O2", "-std=gnu11", "-ffreestanding",
        "-D_POSIX_C_SOURCE=200809L",
        # LeonOS's native stat/fstat use a compact private structure. Keep
        # BusyBox on the Picolibc POSIX ABI through the port's adapter layer.
        "-Dstat=leonos_posix_stat", "-Dfstat=leonos_posix_fstat",
        "-fno-stack-protector", "-fno-pic", "-fno-pie", "-mno-red-zone",
        "-mgeneral-regs-only", "-ffunction-sections", "-fdata-sections",
        "-nostdinc", "-isystem", str(headers),
        "-I" + str(sdk_dir / "busybox-include"),
        "-I" + str(sdk_dir / "picolibc/include"),
        "-I" + str(sdk_dir / "leonos-libc"),
        "-I" + str(sdk_dir / "include"),
    ])
    ldflags = " ".join([
        "-target", "x86_64-unknown-none", "-nostdlib", "-fuse-ld=lld",
        "-Wl,-u,_start", "-Wl,--gc-sections", "-Wl,-T," + str(linker_script),
        "-L" + str(lib_dir),
    ])
    run([
        "make", "-C", str(source_dir), f"O={output_dir}", "CC=clang", "ARCH=x86_64",
        "CFLAGS=" + cflags, "LDFLAGS=" + ldflags, "busybox_unstripped",
    ])

    built = output_dir / "busybox_unstripped"
    if not built.is_file():
        raise SystemExit(f"BusyBox build did not produce {built}")
    output = args.output.resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(built, output)
    args.stamp.parent.mkdir(parents=True, exist_ok=True)
    args.stamp.write_text(
        "{\n"
        f"  \"busybox_commit\": \"{revision}\",\n"
        f"  \"config_sha256\": \"{hashlib.sha256(args.config.read_bytes()).hexdigest()}\"\n"
        "}\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
