#!/usr/bin/env python3
"""Build TinyCC as a static x86_64 LeonOS user-space compiler.

The upstream tree stays pristine.  This script makes a build-owned source
copy, applies the small LeonOS target adaptation there, and stages the
compiler's headers and static runtime beside ``tcc.elf``.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import subprocess
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
TCC_MAIN_SOURCE = "tcc.c"
LIBTCC1_SOURCES = (
    "lib/libtcc1.c",
    "lib/stdatomic.c",
    "lib/builtin.c",
    "lib/atomic.S",
    "lib/alloca.S",
    "lib/alloca-bt.S",
    "lib/va_list.c",
    "lib/dsohandle.c",
)


def run(command: list[str], *, cwd: Path | None = None) -> None:
    subprocess.run(command, cwd=cwd, check=True)


def require_within_root(path: Path, description: str) -> Path:
    resolved = path.resolve()
    try:
        resolved.relative_to(ROOT)
    except ValueError as error:
        raise SystemExit(f"{description} must be inside the LeonOS tree: {resolved}") from error
    if resolved == ROOT:
        raise SystemExit(f"{description} cannot be the LeonOS tree root")
    return resolved


def clang_resource_headers() -> Path:
    result = subprocess.run(
        ["clang", "-print-resource-dir"], check=True, text=True, capture_output=True
    )
    headers = Path(result.stdout.strip()) / "include"
    if not headers.is_dir():
        raise SystemExit(f"Clang resource headers are missing: {headers}")
    return headers


def source_revision(source: Path) -> str:
    result = subprocess.run(
        ["git", "-C", str(source), "rev-parse", "HEAD"],
        check=True,
        text=True,
        capture_output=True,
    )
    return result.stdout.strip()


def replace_once(path: Path, before: str, after: str, description: str) -> None:
    text = path.read_text(encoding="utf-8")
    if text.count(before) != 1:
        raise SystemExit(f"unsupported TinyCC revision: cannot apply {description}")
    path.write_text(text.replace(before, after, 1), encoding="utf-8", newline="\n")


def write_config(path: Path) -> None:
    path.write_text(
        "/* Generated by tools/build_tcc.py for LeonOS. */\n"
        "#define TCC_VERSION \"0.9.28rc-leonos\"\n"
        "#define TCC_TARGET_X86_64 1\n"
        "#define CONFIG_TCC_STATIC 1\n"
        "#define CONFIG_TCC_BACKTRACE 0\n"
        "#define CONFIG_TCC_BCHECK 0\n"
        "/* LeonOS runs a single compiler invocation per process. */\n"
        "#define CONFIG_TCC_SEMLOCK 0\n"
        "#define CONFIG_TCC_PREDEFS 0\n"
        "#define CONFIG_TCCDIR \"0:/programs/tcc\"\n"
        "#define CONFIG_TCC_SWITCHES \"-static\"\n"
        "#define CONFIG_TCC_SYSINCLUDEPATHS \"{B}/include\"\n"
        "#define CONFIG_TCC_LIBPATHS \"{B}/lib\"\n"
        "#define CONFIG_TCC_CRTPREFIX \"{B}/lib\"\n"
        "#define CONFIG_TCC_ELFINTERP \"\"\n",
        encoding="utf-8",
        newline="\n",
    )


def patch_tinycc(source: Path) -> None:
    """Apply the target-only changes to the copied TinyCC source tree."""
    write_config(source / "config.h")

    replace_once(
        source / "tcc.h",
        "# define IS_DIRSEP(c) (c == '/')\n"
        "# define IS_ABSPATH(p) IS_DIRSEP(p[0])\n"
        "# define PATHCMP strcmp\n"
        "# define PATHSEP \":\"\n",
        "# define IS_DIRSEP(c) (c == '/')\n"
        "/* LeonOS drive paths (for example 0:/programs) are absolute. */\n"
        "# define IS_ABSPATH(p) (IS_DIRSEP(p[0]) || \\\n"
        "                         (p[0] && p[1] == ':' && IS_DIRSEP(p[2])))\n"
        "# define PATHCMP strcmp\n"
        "/* ':' is part of every LeonOS absolute path. */\n"
        "# define PATHSEP \";\"\n",
        "LeonOS path syntax",
    )
    replace_once(
        source / "tcc.h",
        "#endif\n\n#if defined CONFIG_TCC_BACKTRACE && CONFIG_TCC_BACKTRACE==0\n",
        "#endif\n\n/* TCC is hosted by LeonOS but cannot execute generated memory images. */\n"
        "#ifdef LEONOS_TCC_PORT\n"
        "# undef TCC_IS_NATIVE\n"
        "#endif\n\n#if defined CONFIG_TCC_BACKTRACE && CONFIG_TCC_BACKTRACE==0\n",
        "disable native in-memory execution",
    )

    tccelf = source / "tccelf.c"
    text = tccelf.read_text(encoding="utf-8")
    begin = text.index("ST_FUNC void tccelf_add_crtbegin(TCCState *s1)")
    end_marker = "#endif /* TCC_TARGET_UNIX */"
    end = text.index(end_marker, begin) + len(end_marker)
    replacement = """ST_FUNC void tccelf_add_crtbegin(TCCState *s1)
{
    /* LeonOS uses its existing crt0 and static Picolibc/LeonOS archives. */
    if (s1->output_type != TCC_OUTPUT_DLL) {
        tcc_add_crt(s1, \"crt0.o\");
        /* Picolibc strtold() needs the target 128-bit conversion helpers. */
        tcc_add_crt(s1, \"leonos_tcc_runtime.o\");
    }
}

ST_FUNC void tccelf_add_crtend(TCCState *s1)
{
    (void)s1;
}
#endif /* TCC_TARGET_UNIX */"""
    tccelf.write_text(text[:begin] + replacement + text[end:], encoding="utf-8", newline="\n")
    replace_once(
        tccelf,
        "        tcc_add_library(s1, \"c\");\n",
        "        tcc_add_library(s1, \"leonos\");\n"
        "        tcc_add_library(s1, \"picolibc\");\n",
        "LeonOS static runtime libraries",
    )

    replace_once(
        source / "tcc.c",
        "    if (n == 0) {\n",
        "    if (s->output_type == TCC_OUTPUT_MEMORY) {\n"
        "        tcc_error_noabort(\"-run is not supported on LeonOS\");\n"
        "    } else if (s->output_type == TCC_OUTPUT_DLL ||\n"
        "               (s->output_type & TCC_OUTPUT_DYN)) {\n"
        "        tcc_error_noabort(\"dynamic linking is not supported on LeonOS\");\n"
        "    }\n\n"
        "    if (n == 0) {\n",
        "reject unavailable LeonOS output modes",
    )


def compile_source(flags: list[str], source: Path, output: Path) -> None:
    run(["clang", *flags, "-c", str(source), "-o", str(output)])


def copy_headers(picolibc_include: Path, sdk_include: Path, tcc_source: Path,
                 port: Path, runtime_include: Path) -> None:
    shutil.copytree(picolibc_include, runtime_include)
    for source in sorted(sdk_include.rglob("*")):
        if not source.is_file():
            continue
        relative = source.relative_to(sdk_include)
        destination = runtime_include / relative
        # Picolibc owns the ISO C headers.  The SDK contributes LeonOS headers
        # and compatibility-only files that Picolibc does not supply.
        if destination.exists() and relative.parts[0] != "leonos":
            continue
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(source, destination)
    # Picolibc intentionally does not install a few compiler-owned headers
    # such as stddef.h and stdarg.h.  TCC supplies these target definitions;
    # they must live in the same private sysroot as the C library headers.
    for source in sorted((tcc_source / "include").iterdir()):
        if source.is_file():
            shutil.copyfile(source, runtime_include / source.name)
    shutil.copyfile(tcc_source / "tcclib.h", runtime_include / "tcclib.h")
    # Picolibc's generic machine types expect GCC/Clang builtin type macros.
    # TinyCC has the x86_64 ABI internally but does not expose all of them to
    # preprocessing, so stage the LeonOS-specific bridge last as
    # <machine/_types.h>.
    shutil.copyfile(port / "leonos_machine_types.h",
                    runtime_include / "machine" / "_types.h")


def runtime_manifest(runtime_dir: Path) -> dict[str, str]:
    result: dict[str, str] = {}
    for path in sorted(runtime_dir.rglob("*")):
        if path.is_file():
            result[path.relative_to(runtime_dir).as_posix()] = hashlib.sha256(path.read_bytes()).hexdigest()
    return result


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--port", type=Path, required=True)
    parser.add_argument("--sdk-include", type=Path, required=True)
    parser.add_argument("--picolibc-prefix", type=Path, required=True)
    parser.add_argument("--leonos-lib", type=Path, required=True)
    parser.add_argument("--picolibc-lib", type=Path, required=True)
    parser.add_argument("--linker-script", type=Path, required=True)
    parser.add_argument("--work-dir", type=Path, required=True)
    parser.add_argument("--runtime-dir", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--stamp", type=Path, required=True)
    args = parser.parse_args()

    if os.name == "nt":
        raise SystemExit("TinyCC must be built from WSL/Linux, not Windows")

    source = args.source.resolve()
    port = args.port.resolve()
    sdk_include = args.sdk_include.resolve()
    picolibc_prefix = args.picolibc_prefix.resolve()
    leonos_lib = args.leonos_lib.resolve()
    picolibc_lib = args.picolibc_lib.resolve()
    linker_script = args.linker_script.resolve()
    work_dir = require_within_root(args.work_dir, "TinyCC work directory")
    runtime_dir = require_within_root(args.runtime_dir, "TinyCC runtime directory")
    output = require_within_root(args.output, "TinyCC output")
    stamp = require_within_root(args.stamp, "TinyCC stamp")
    picolibc_include = picolibc_prefix / "include"
    required = (
        source / TCC_MAIN_SOURCE, source / "COPYING", source / "include/tccdefs.h",
        port / "leonos_tcc_shim.c", port / "leonos_machine_types.h", port / "README.md",
        port / "examples/hello.c", sdk_include,
        picolibc_include, leonos_lib, picolibc_lib, linker_script,
    )
    for path in required:
        if not path.exists():
            raise SystemExit(f"required TinyCC build input is missing: {path}")

    if work_dir.exists():
        shutil.rmtree(work_dir)
    work_source = work_dir / "source"
    shutil.copytree(source, work_source, ignore=shutil.ignore_patterns(".git"))
    patch_tinycc(work_source)
    object_dir = work_dir / "objects"
    object_dir.mkdir()

    headers = clang_resource_headers()
    flags = [
        "-target", "x86_64-unknown-none", "-O2", "-std=c11", "-ffreestanding",
        "-fno-stack-protector", "-fno-pic", "-fno-pie", "-mno-red-zone",
        # TinyCC parses long-double literals internally.  The kernel saves
        # x87/SSE state for every user task, so its compiler process may use
        # the x86 floating-point unit even though most LeonOS apps do not.
        "-ffunction-sections", "-fdata-sections", "-Wall",
        "-Wextra", "-Wno-unused-parameter", "-DLEONOS_TCC_PORT=1",
        "-DLEONOS_USE_PICOLIBC", "-D_POSIX_C_SOURCE=200809L", "-nostdinc",
        "-isystem", str(headers), "-I" + str(work_source),
        "-I" + str(picolibc_include), "-I" + str(sdk_include),
    ]
    tcc_object = object_dir / "tcc.o"
    compile_source(flags + ["-DONE_SOURCE=1"], work_source / TCC_MAIN_SOURCE, tcc_object)
    shim_object = object_dir / "leonos_tcc_shim.o"
    compile_source(flags, port / "leonos_tcc_shim.c", shim_object)

    libtcc1_objects: list[Path] = []
    for relative in LIBTCC1_SOURCES:
        source_file = work_source / relative
        object_file = object_dir / (relative.replace("/", "_").rsplit(".", 1)[0] + ".o")
        compile_source(flags + ["-I" + str(work_source / "lib")], source_file, object_file)
        libtcc1_objects.append(object_file)
    libtcc1 = work_dir / "libtcc1.a"
    run(["llvm-ar", "rcs", str(libtcc1), *map(str, libtcc1_objects)])

    output.parent.mkdir(parents=True, exist_ok=True)
    run([
        "ld.lld", "-nostdlib", "--gc-sections", "-z", "max-page-size=0x1000",
        "-T", str(linker_script), "-o", str(output), str(tcc_object), str(shim_object),
        "--start-group", str(leonos_lib), str(picolibc_lib), "--end-group",
    ])

    staging_dir = runtime_dir.with_name(runtime_dir.name + ".new")
    if staging_dir.exists():
        shutil.rmtree(staging_dir)
    (staging_dir / "lib").mkdir(parents=True)
    copy_headers(picolibc_include, sdk_include, work_source, port,
                 staging_dir / "include")
    shutil.copyfile(libtcc1, staging_dir / "lib/libtcc1.a")
    shutil.copyfile(leonos_lib, staging_dir / "lib/libleonos.a")
    shutil.copyfile(picolibc_lib, staging_dir / "lib/libpicolibc.a")
    shutil.copyfile(object_dir / "lib_alloca.o", staging_dir / "lib/alloca.o")
    shutil.copyfile(shim_object, staging_dir / "lib/leonos_tcc_runtime.o")
    # The installed crt0 deliberately remains a normal relocatable object.
    run([
        "clang", "-target", "x86_64-unknown-none", "-ffreestanding", "-mno-red-zone",
        "-mgeneral-regs-only", "-c", str(ROOT / "userland/libc/src/crt0.S"),
        "-o", str(staging_dir / "lib/crt0.o"),
    ])
    shutil.copyfile(source / "COPYING", staging_dir / "COPYING")
    shutil.copyfile(port / "README.md", staging_dir / "README-LEONOS.md")
    shutil.copytree(port / "examples", staging_dir / "examples")

    if runtime_dir.exists():
        shutil.rmtree(runtime_dir)
    staging_dir.rename(runtime_dir)
    stamp.parent.mkdir(parents=True, exist_ok=True)
    stamp.write_text(
        json.dumps(
            {
                "tinycc_commit": source_revision(source),
                "target": "x86_64-leonos-static",
                "runtime": runtime_manifest(runtime_dir),
                "port_sha256": hashlib.sha256(
                    (port / "leonos_tcc_shim.c").read_bytes() + (port / "README.md").read_bytes()
                ).hexdigest(),
            },
            indent=2,
            sort_keys=True,
        ) + "\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
