#!/usr/bin/env python3
"""Generate native x86-64 numbers from the pinned Linux v6.12 syscall table."""

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def syscall_entries():
    for line in (ROOT / "tools/abi/linux-v6.12-syscall_64.tbl").read_text().splitlines():
        fields = line.partition("#")[0].split()
        if len(fields) >= 3 and fields[1] in ("common", "64"):
            yield int(fields[0]), fields[2]


def header():
    entries = list(syscall_entries())
    assert len(entries) == 375
    lines = ["/* Generated by tools/generate_linux_syscalls.py; Linux v6.12. */",
             "#ifndef LEONOS_UAPI_LINUX_SYSCALL_H", "#define LEONOS_UAPI_LINUX_SYSCALL_H", ""]
    lines += [f"#define __NR_{name} {number}" for number, name in entries]
    lines += ["", "/* libc API aliases do not allocate additional syscall numbers. */"]
    lines += [f"#define SYS_{name} __NR_{name}" for _, name in entries]
    lines += ["", "#endif", ""]
    return "\n".join(lines)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    target = ROOT / "include/uapi/linux/syscall.h"
    if args.check:
        if target.read_text() != header():
            raise SystemExit("stale Linux syscall UAPI; run tools/generate_linux_syscalls.py")
    else:
        target.write_text(header())
