#!/usr/bin/env python3
"""Validate the component manifest and generate its Kconfig menu."""

from __future__ import annotations

import argparse
import sys
from collections import defaultdict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from buildsystem.components import (
    Component,
    ComponentError,
    component_json,
    load_components,
    validate_component_targets,
)


def kconfig_quote(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def generated_symbol(symbol: str, suffix: str) -> str:
    return f"LEON_COMPONENT_{symbol}_{suffix}"


def generate(components: tuple[Component, ...]) -> str:
    by_id = {component.id: component for component in components}
    categories: dict[str, list[Component]] = defaultdict(list)
    for component in components:
        if not component.required:
            categories[component.category].append(component)
    lines = [
        "# This file is generated by tools/generate_component_kconfig.py.",
        "# Edit configs/components.toml instead.",
        "",
    ]
    for category in sorted(categories):
        lines.extend([f'menu "{kconfig_quote(category)}"', ""])
        for component in categories[category]:
            build = generated_symbol(component.symbol, "BUILD")
            label = kconfig_quote(component.label)
            lines.extend([
                f"config {build}",
                f'    bool "Build {label}"',
                f"    default {'y' if component.default else 'n'}",
            ])
            for dependency in component.depends:
                dependency_component = by_id[dependency]
                # Dependencies are selected transitively by Kconfig.  A
                # visible `depends on` makes an otherwise valid example
                # disappear when its library is disabled, while `select`
                # expresses the manifest's auto-enable contract.
                if not dependency_component.required:
                    lines.append(
                        f"    select {generated_symbol(dependency_component.symbol, 'BUILD')}"
                    )
            lines.append("")
            option_specs = [
                ("IMAGE", component.stage, f"Include {label} in system images"),
                ("ENTRY", component.entry, f"Generate a desktop entry for {label}"),
                ("SDK", component.sdk, f"Include {label} in the developer SDK"),
            ]
            # Only package-producing components expose an API switch. Some
            # manifest entries have api=true solely because another package
            # requires them and are enabled internally by api_requires.
            if component.api and component.api_stage_path:
                option_specs.append(("API", True, f"Build the API package for {label}"))
            for suffix, default, text in option_specs:
                lines.extend([
                    f"config {generated_symbol(component.symbol, suffix)}",
                    f'    bool "{text}"',
                    f"    default {'y' if default else 'n'}",
                    f"    depends on {build}",
                ])
                lines.append("")
        lines.extend(["endmenu", ""])
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", default="configs/components.toml")
    parser.add_argument("--output", default="Kconfig.components")
    parser.add_argument("--json", dest="json_output", help="write validated manifest as JSON")
    args = parser.parse_args(argv)
    try:
        components = load_components(ROOT / args.manifest)
        validate_component_targets(components, ROOT)
        text = generate(components)
    except ComponentError as exc:
        print(f"component manifest: {exc}", file=sys.stderr)
        return 1
    output = ROOT / args.output
    output.parent.mkdir(parents=True, exist_ok=True)
    if not output.exists() or output.read_text(encoding="utf-8") != text:
        output.write_text(text, encoding="utf-8", newline="\n")
    if args.json_output:
        json_output = ROOT / args.json_output
        json_output.parent.mkdir(parents=True, exist_ok=True)
        json_output.write_text(component_json(components) + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
