#!/usr/bin/env python3
"""Generate Doxygen documentation for the LeonOS kernel and middle layer.

The generated site is intentionally kept under ``tools/dist`` so the source
tree stays clean and the output can be discarded or regenerated at any time.
Run this script from any working directory; paths are resolved from the
repository root next to this file.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "tools" / "dist"
INPUTS = (ROOT / "kernel" / "ntclks", ROOT / "middlelayer" / "osmlayer")


def _doxygen_quote(path: Path) -> str:
    """Return a Doxygen config string for a filesystem path."""
    return '"' + path.resolve().as_posix().replace('"', r'\"') + '"'


def _config_text(output: Path) -> str:
    """Build the self-contained Doxygen configuration used for one run."""
    inputs = " ".join(_doxygen_quote(path) for path in INPUTS)
    return f"""# Generated by tools/generate_doxygen.py. Do not edit.
PROJECT_NAME           = LeonOS 4 kernel and middle layer
PROJECT_BRIEF          = Kernel and osmlayer API and implementation reference
OUTPUT_DIRECTORY       = {_doxygen_quote(output)}
CREATE_SUBDIRS         = NO
OUTPUT_LANGUAGE        = English
INPUT                  = {inputs}
FILE_PATTERNS          = *.c *.h *.S *.rs
RECURSIVE              = YES
EXTENSION_MAPPING      = rs=C
EXCLUDE_PATTERNS       = */build/* */target/* */.git/*
EXTRACT_ALL            = YES
EXTRACT_PRIVATE        = YES
EXTRACT_STATIC         = YES
WARN_IF_UNDOCUMENTED   = NO
WARN_IF_DOC_ERROR      = YES
WARN_NO_PARAMDOC       = NO
FULL_PATH_NAMES        = YES
STRIP_FROM_PATH        = {_doxygen_quote(ROOT)}
GENERATE_HTML          = YES
HTML_OUTPUT            = html
GENERATE_XML           = YES
XML_OUTPUT             = xml
GENERATE_LATEX         = NO
GENERATE_MAN           = NO
GENERATE_RTF           = NO
GENERATE_DOCBOOK       = NO
HAVE_DOT               = NO
CALL_GRAPH             = NO
CALLER_GRAPH           = NO
HTML_TIMESTAMP         = NO
QUIET                  = NO
"""


def _validate_inputs() -> None:
    """Ensure both documented source trees exist before invoking Doxygen."""
    missing = [path for path in INPUTS if not path.is_dir()]
    if missing:
        names = ", ".join(str(path.relative_to(ROOT)) for path in missing)
        raise SystemExit(f"Doxygen input directory is missing: {names}")


def _clear_generated_output(output: Path) -> None:
    """Remove only directories owned by this generator from the output root."""
    output.mkdir(parents=True, exist_ok=True)
    for name in ("html", "xml", "latex", "man", "rtf", "docbook"):
        shutil.rmtree(output / name, ignore_errors=True)


def main(argv: list[str] | None = None) -> int:
    """Generate the documentation site and return a process status code."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--doxygen",
        default="doxygen",
        help="Doxygen executable to run (default: doxygen)",
    )
    parser.add_argument(
        "--keep-config",
        action="store_true",
        help="Keep the generated Doxygen configuration as tools/dist/Doxyfile",
    )
    args = parser.parse_args(argv)

    _validate_inputs()
    executable = shutil.which(args.doxygen) if not Path(args.doxygen).is_file() else args.doxygen
    if executable is None:
        raise SystemExit(
            "Doxygen was not found; install Doxygen or pass --doxygen PATH"
        )
    _clear_generated_output(OUTPUT)
    config_path: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w", encoding="utf-8", newline="\n", suffix=".doxyfile",
            dir=OUTPUT, delete=False,
        ) as config:
            config.write(_config_text(OUTPUT))
            config_path = Path(config.name)
        if args.keep_config:
            kept = OUTPUT / "Doxyfile"
            shutil.copyfile(config_path, kept)
        subprocess.run([executable, str(config_path)], cwd=ROOT, check=True)
    except subprocess.CalledProcessError as exc:
        return exc.returncode or 1
    finally:
        if config_path is not None:
            config_path.unlink(missing_ok=True)

    print(f"Doxygen documentation generated at {OUTPUT / 'html' / 'index.html'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
