#!/usr/bin/env python3
"""Generate the GBK two-byte mapping table used by the userland text API."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


TABLE_SIZE = 23940


def read_values(source: Path) -> list[int]:
    text = source.read_text(encoding="utf-8")
    match = re.search(
        r"int\s+gb18030_decoder::m_index\[\]\s*=\s*\{(.*?)\n\s*\};",
        text,
        re.DOTALL,
    )
    if not match:
        raise ValueError(f"could not find the GB18030 index in {source}")
    values = [0 if value == "null" else int(value)
              for value in re.findall(r"\b(?:null|[0-9]+)\b", match.group(1))]
    if len(values) < TABLE_SIZE:
        raise ValueError(f"expected at least {TABLE_SIZE} GBK entries, found {len(values)}")
    # GBK has exactly 126 * 190 two-byte pointer positions.  The embedded
    # upstream table currently has extra, unreachable entries after this range.
    return values[:TABLE_SIZE]


def render(values: list[int]) -> str:
    reverse_pointers = [pointer for _, pointer in sorted(
        (codepoint, pointer) for pointer, codepoint in enumerate(values) if codepoint
    )]
    lines = [
        "/* Generated by tools/generate_gbk_table.py. Do not edit. */",
        "#ifndef LEONOS_GENERATED_GBK_TABLE_H",
        "#define LEONOS_GENERATED_GBK_TABLE_H",
        "",
        "#include <stdint.h>",
        "",
        f"#define LEONOS_GBK_POINTER_COUNT {TABLE_SIZE}u",
        f"#define LEONOS_GBK_MAPPED_COUNT {len(reverse_pointers)}u",
        "",
        "static const uint32_t leonos_gbk_to_unicode[LEONOS_GBK_POINTER_COUNT] = {",
    ]
    for start in range(0, len(values), 12):
        lines.append("    " + ", ".join(f"{value}u" for value in values[start:start + 12]) + ",")
    lines += [
        "};",
        "",
        "/* Pointers sorted by Unicode code point for GBK encoding lookups. */",
        "static const uint16_t leonos_gbk_unicode_pointers[LEONOS_GBK_MAPPED_COUNT] = {",
    ]
    for start in range(0, len(reverse_pointers), 16):
        lines.append("    " + ", ".join(f"{value}u" for value in reverse_pointers[start:start + 16]) + ",")
    lines += [
        "};",
        "",
        "#endif",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    output = args.output.resolve()
    generated = render(read_values(args.source.resolve()))
    output.parent.mkdir(parents=True, exist_ok=True)
    if not output.exists() or output.read_text(encoding="utf-8") != generated:
        output.write_text(generated, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
