#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
KNOWN_KEYS = {
    "CONFIG_VMDK_DEFAULT_LANGUAGE_EN": "y",
    "CONFIG_VMDK_DEFAULT_LANGUAGE_ZH": "n",
    "CONFIG_VMDK_REQUIRE_LICENSE": "y",
    "CONFIG_INSTALLER_INSTALLED_REQUIRE_LICENSE": "y",
    "CONFIG_IMAGE_SIZE_MIB": "192",
    "CONFIG_INSTALLER_ROOT_SIZE_MIB": "128",
    "CONFIG_QEMU_MEMORY_MB": "512",
    "CONFIG_QEMU_DISPLAY_WIDTH": "1920",
    "CONFIG_QEMU_DISPLAY_HEIGHT": "1080",
    "CONFIG_QEMU_ENABLE_KVM": "y",
    "CONFIG_QEMU_NET_DEVICE": '"e1000"',
    "CONFIG_QEMU_OVMF_PATH": '"/usr/share/ovmf/OVMF.fd"',
    "CONFIG_LICENSE_SERVER_URL": '"http://127.0.0.1:30301"',
    "CONFIG_LICENSE_DEBUG_LOG": "y",
}

STRING_KEYS = {
    "CONFIG_LICENSE_SERVER_URL",
    "CONFIG_QEMU_NET_DEVICE",
    "CONFIG_QEMU_OVMF_PATH",
}


def parse_config(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            if line.startswith("# CONFIG_") and line.endswith(" is not set"):
                key = line[2 : -len(" is not set")]
                if key in KNOWN_KEYS:
                    values[key] = "n"
            continue
        if "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        if key in KNOWN_KEYS:
            values[key] = value.strip()
    return values


def bool_value(values: dict[str, str], key: str) -> bool:
    return values.get(key, KNOWN_KEYS[key]) == "y"


def string_value(values: dict[str, str], key: str) -> str:
    value = values.get(key, KNOWN_KEYS[key]).strip()
    if len(value) >= 2 and value[0] == '"' and value[-1] == '"':
        value = value[1:-1]
    return value.replace('\\"', '"').replace("\\\\", "\\")


def c_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def normalize_values(values: dict[str, str]) -> dict[str, str]:
    normalized = dict(KNOWN_KEYS)
    for key, value in values.items():
        if key in KNOWN_KEYS:
            normalized[key] = value
    return normalized


def write_config(path: Path, values: dict[str, str]) -> None:
    lines = []
    for key in KNOWN_KEYS:
        value = values[key]
        if value == "n":
            lines.append(f"# {key} is not set")
        else:
            lines.append(f"{key}={value}")
    write_if_changed(path, "\n".join(lines) + "\n")


def write_if_changed(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    try:
        if path.read_text(encoding="utf-8") == text:
            return
    except FileNotFoundError:
        pass
    path.write_text(text, encoding="utf-8")


def write_header(path: Path, guard: str, values: dict[str, str], require_key: str) -> None:
    header_lines = [
        "/* Generated by tools/kconfig_sync.py. */",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
    ]

    for key in sorted(values):
        value = values[key]
        if value == "y":
            header_lines.append(f"#define {key} 1")
        elif value == "n":
            continue
        elif key in STRING_KEYS:
            header_lines.append(f"#define {key} {c_string(string_value(values, key))}")
        else:
            header_lines.append(f"#define {key} {value}")

    header_lines.extend([
        "",
        f"#define LEONOS_LICENSE_REQUIRE {1 if bool_value(values, require_key) else 0}",
    ])
    header_lines.extend(["", "#endif", ""])
    write_if_changed(path, "\n".join(header_lines))


def write_outputs(values: dict[str, str], generated: Path) -> None:
    generated.mkdir(parents=True, exist_ok=True)

    header = generated / "autoconf.h"
    installer_header = generated / "autoconf-installer.h"
    rustcfg = generated / "rustcfg.args"

    rust_lines: list[str] = []
    for key in sorted(values):
        if values[key] == "y":
            rust_lines.append(f'--cfg={key.lower()}')

    write_header(header, "LEONOS4_AUTOCONF_H", values, "CONFIG_VMDK_REQUIRE_LICENSE")
    write_header(
        installer_header,
        "LEONOS4_AUTOCONF_INSTALLER_H",
        values,
        "CONFIG_INSTALLER_INSTALLED_REQUIRE_LICENSE",
    )
    write_if_changed(rustcfg, "\n".join(rust_lines) + ("\n" if rust_lines else ""))


def main() -> int:
    parser = argparse.ArgumentParser(description="Synchronize LeonOS 4 Kconfig outputs")
    parser.add_argument("--config", default=".config")
    parser.add_argument("--defaults", default="configs/default.conf")
    parser.add_argument("--out-dir", default="include/generated")
    args = parser.parse_args()

    config = ROOT / args.config
    defaults = ROOT / args.defaults
    generated = ROOT / args.out_dir

    if not config.exists():
        config.write_text(defaults.read_text(encoding="utf-8"), encoding="utf-8")

    values = normalize_values(parse_config(config))
    write_config(config, values)
    write_outputs(values, generated)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
