#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def parse_config(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip()
    return values


def write_outputs(values: dict[str, str]) -> None:
    generated = ROOT / "include" / "generated"
    generated.mkdir(parents=True, exist_ok=True)

    header = generated / "autoconf.h"
    rustcfg = generated / "rustcfg.args"

    header_lines = [
        "/* Generated by tools/kconfig_sync.py. */",
        "#ifndef LEONOS4_AUTOCONF_H",
        "#define LEONOS4_AUTOCONF_H",
        "",
    ]
    rust_lines: list[str] = []

    for key in sorted(values):
        value = values[key]
        if value == "y":
            header_lines.append(f"#define {key} 1")
            rust_lines.append(f'--cfg={key.lower()}')
        else:
            header_lines.append(f"#define {key} {value}")

    header_lines.extend(["", "#endif", ""])
    header.write_text("\n".join(header_lines), encoding="utf-8")
    rustcfg.write_text("\n".join(rust_lines) + ("\n" if rust_lines else ""), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Synchronize LeonOS 4 Kconfig outputs")
    parser.add_argument("--config", default=".config")
    parser.add_argument("--defaults", default="configs/default.conf")
    args = parser.parse_args()

    config = ROOT / args.config
    defaults = ROOT / args.defaults

    if not config.exists():
        config.write_text(defaults.read_text(encoding="utf-8"), encoding="utf-8")

    values = parse_config(config)
    write_outputs(values)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
