#!/usr/bin/env python3
"""Synchronize Kconfig values, generated headers, and component selection."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from buildsystem.components import (
    Component,
    component_config_symbols,
    component_defaults,
    load_components,
    resolve_components,
    validate_component_targets,
)


BUILD_PRESET_CHOICES = (
    "CONFIG_BUILD_PRESET_DEBUG",
    "CONFIG_BUILD_PRESET_DEVELOP",
    "CONFIG_BUILD_PRESET_RELEASE",
)
BUILD_PRESET_VALUES = {
    "CONFIG_BUILD_PRESET_DEBUG": {
        "CONFIG_BUILD_OPTIMIZATION_LEVEL": "0",
        "CONFIG_BUILD_DEBUG_SYMBOLS": "y",
        "CONFIG_BUILD_ENABLE_LTO": "n",
        "CONFIG_BUILD_STRIP_BINARIES": "n",
        "CONFIG_BUILD_DEVELOPER_DIAGNOSTICS": "y",
    },
    "CONFIG_BUILD_PRESET_DEVELOP": {
        "CONFIG_BUILD_OPTIMIZATION_LEVEL": "2",
        "CONFIG_BUILD_DEBUG_SYMBOLS": "y",
        "CONFIG_BUILD_ENABLE_LTO": "n",
        "CONFIG_BUILD_STRIP_BINARIES": "n",
        "CONFIG_BUILD_DEVELOPER_DIAGNOSTICS": "n",
    },
    "CONFIG_BUILD_PRESET_RELEASE": {
        "CONFIG_BUILD_OPTIMIZATION_LEVEL": "3",
        "CONFIG_BUILD_DEBUG_SYMBOLS": "n",
        "CONFIG_BUILD_ENABLE_LTO": "n",
        "CONFIG_BUILD_STRIP_BINARIES": "y",
        "CONFIG_BUILD_DEVELOPER_DIAGNOSTICS": "n",
    },
}


def parse_config(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line:
            continue
        if line.startswith("# CONFIG_") and line.endswith(" is not set"):
            values[line[2 : -len(" is not set")]] = "n"
            continue
        if "=" in line and not line.startswith("#"):
            key, value = line.split("=", 1)
            key = key.strip()
            if key.startswith("CONFIG_"):
                values[key] = value.strip()
    return values


def config_key_order(path: Path) -> list[str]:
    values = parse_config(path)
    return list(values)


def bool_value(values: dict[str, str], key: str) -> bool:
    return values.get(key) == "y"


def string_value(value: str) -> str:
    value = value.strip()
    if len(value) >= 2 and value[0] == '"' and value[-1] == '"':
        value = value[1:-1]
    return value.replace('\\"', '"').replace("\\\\", "\\")


def c_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def normalize_values(
    defaults: dict[str, str],
    configured: dict[str, str],
    component_values: dict[str, str],
) -> dict[str, str]:
    normalized = {**defaults, **component_values}
    for key, value in configured.items():
        if key in normalized:
            normalized[key] = value
    preset = next(
        (key for key in BUILD_PRESET_CHOICES if normalized.get(key) == "y"),
        "CONFIG_BUILD_PRESET_DEVELOP",
    )
    if normalized.get("CONFIG_BUILD_USE_ADVANCED_OVERRIDES") != "y":
        normalized.update(BUILD_PRESET_VALUES[preset])
    return normalized


def validate_configured_keys(
    configured: dict[str, str], defaults: dict[str, str], components: tuple[Component, ...]
) -> None:
    known = set(defaults) | component_config_symbols(components)
    unknown = sorted(key for key in configured if key not in known)
    if unknown:
        raise ValueError("unknown configuration symbol(s): " + ", ".join(unknown))


def write_if_changed(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    try:
        if path.read_text(encoding="utf-8") == text:
            return
    except FileNotFoundError:
        pass
    path.write_text(text, encoding="utf-8", newline="\n")


def write_config(path: Path, values: dict[str, str], ordered_keys: list[str]) -> None:
    keys = [key for key in ordered_keys if key in values]
    keys.extend(sorted(key for key in values if key not in set(keys)))
    lines = [
        f"# {key} is not set" if values[key] == "n" else f"{key}={values[key]}"
        for key in keys
    ]
    write_if_changed(path, "\n".join(lines) + "\n")


def write_header(path: Path, guard: str, values: dict[str, str], require_key: str) -> None:
    lines = [
        "/* Generated by tools/kconfig_sync.py. */",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
    ]
    for key in sorted(values):
        value = values[key]
        if value == "y":
            lines.append(f"#define {key} 1")
        elif value == "n":
            continue
        elif value.startswith('"') and value.endswith('"'):
            lines.append(f"#define {key} {c_string(string_value(value))}")
        else:
            lines.append(f"#define {key} {value}")
    lines.extend([
        "",
        f"#define LEONOS_LICENSE_REQUIRE {1 if bool_value(values, require_key) else 0}",
        "",
        "#endif",
        "",
    ])
    write_if_changed(path, "\n".join(lines))


def write_outputs(
    values: dict[str, str],
    generated: Path,
    selection_out: Path,
    selection: dict[str, dict[str, object]],
) -> None:
    generated.mkdir(parents=True, exist_ok=True)
    write_header(
        generated / "autoconf.h",
        "LEONOS4_AUTOCONF_H",
        values,
        "CONFIG_VMDK_REQUIRE_LICENSE",
    )
    write_header(
        generated / "autoconf-installer.h",
        "LEONOS4_AUTOCONF_INSTALLER_H",
        values,
        "CONFIG_INSTALLER_INSTALLED_REQUIRE_LICENSE",
    )
    rust_lines = [
        f"--cfg={key.lower()}" for key in sorted(values) if values[key] == "y"
    ]
    write_if_changed(
        generated / "rustcfg.args",
        "\n".join(rust_lines) + ("\n" if rust_lines else ""),
    )
    payload = {"version": 1, "components": selection}
    write_if_changed(
        selection_out,
        json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", default="buildsystem/config/leonos.conf")
    parser.add_argument("--defaults", default="configs/default.conf")
    parser.add_argument("--manifest", default="configs/components.toml")
    parser.add_argument("--out-dir", default="build/include/generated")
    parser.add_argument("--selection-out", default="build/generated/component-selection.json")
    args = parser.parse_args()

    config = ROOT / args.config
    defaults_path = ROOT / args.defaults
    components = load_components(ROOT / args.manifest)
    validate_component_targets(components, ROOT)
    defaults = parse_config(defaults_path)
    configured = parse_config(config)
    validate_configured_keys(configured, defaults, components)
    values = normalize_values(defaults, configured, component_defaults(components))
    selection = resolve_components(components, values)
    for component in components:
        resolved = selection[component.id]
        values[component.build_symbol] = "y" if resolved["build"] else "n"
        for suffix, field in (
            ("IMAGE", "image"),
            ("ENTRY", "entry"),
            ("SDK", "sdk"),
            ("API", "api"),
        ):
            values[component.option_symbol(suffix)] = "y" if resolved[field] else "n"

    write_config(config, values, config_key_order(defaults_path))
    write_outputs(values, ROOT / args.out_dir, ROOT / args.selection_out, selection)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
