#ifndef EVENT2_EVENT_CONFIG_H_INCLUDED_
#define EVENT2_EVENT_CONFIG_H_INCLUDED_

#define EVENT__NUMERIC_VERSION 0x02010c00
#define EVENT__PACKAGE_VERSION "2.1.12-stable"
#define EVENT__VERSION_MAJOR 2
#define EVENT__VERSION_MINOR 1
#define EVENT__VERSION_PATCH 12
#define EVENT__VERSION "2.1.12-stable"
#define EVENT__PACKAGE "libevent"

#define EVENT__DISABLE_DEBUG_MODE 1
#define EVENT__DISABLE_THREAD_SUPPORT 1
#define EVENT__HAVE_CLOCK_GETTIME 1
#define EVENT__HAVE_ARC4RANDOM 1
#define EVENT__HAVE_ARC4RANDOM_BUF 1
#define EVENT__HAVE_STDINT_H 1
#define EVENT__HAVE_STDDEF_H 1
#define EVENT__HAVE_ERRNO_H 1
#define EVENT__HAVE_UINT64_T 1
#define EVENT__HAVE_UINT32_T 1
#define EVENT__HAVE_UINT16_T 1
#define EVENT__HAVE_UINT8_T 1
#define EVENT__HAVE_FCNTL 1
#define EVENT__HAVE_FCNTL_H 1
#define EVENT__HAVE_GETTIMEOFDAY 1
#define EVENT__HAVE_NANOSLEEP 1
#define EVENT__HAVE_NETDB_H 1
#define EVENT__HAVE_PIPE 1
#define EVENT__HAVE_POLL 1
#define EVENT__HAVE_SIGACTION 1
#define EVENT__HAVE_STDARG_H 1
#define EVENT__HAVE_STDLIB_H 1
#define EVENT__HAVE_STRINGS_H 1
#define EVENT__HAVE_STRING_H 1
#define EVENT__HAVE_STRUCT_TIMESPEC 1
#define EVENT__HAVE_SYS_SOCKET_H 1
#define EVENT__HAVE_SYS_STAT_H 1
#define EVENT__HAVE_SYS_TIME_H 1
#define EVENT__HAVE_SYS_TYPES_H 1
#define EVENT__HAVE_SA_FAMILY_T 1
#define EVENT__HAVE_STRUCT_IN6_ADDR 1
#define EVENT__HAVE_STRUCT_SOCKADDR_IN6 1
#define EVENT__HAVE_STRUCT_SOCKADDR_IN 1
#define EVENT__HAVE_STRUCT_SOCKADDR_STORAGE 1
#define EVENT__HAVE_UNISTD_H 1
#define EVENT__HAVE___func__ 1
#define EVENT__SIZEOF_INT 4
#define EVENT__SIZEOF_LONG 8
#define EVENT__SIZEOF_LONG_LONG 8
#define EVENT__SIZEOF_OFF_T 8
#define EVENT__SIZEOF_PID_T 4
#define EVENT__SIZEOF_SIZE_T 8
#define EVENT__SIZEOF_VOID_P 8

#endif
