name: Build LeonOS Installer

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update

          sudo apt-get install -y \
            ninja-build \
            clang \
            llvm \
            lld \
            grub-efi-amd64-bin \
            grub-pc-bin \
            grub-common \
            xorriso \
            mtools \
            dosfstools \
            ovmf \
            qemu-system-x86 \
            python3 \
            python3-pip \
            python3-pil \
            git \
            make \
            curl

      - name: Install Rust
        run: |
          rustup toolchain install stable
          rustup default stable
          rustup target add x86_64-unknown-none

      - name: Verify toolchain
        run: |
          clang --version
          ld.lld --version
          llvm-ar --version
          rustc --version
          cargo --version
          ninja --version

      - name: Prepare build configuration
        run: |
          cp configs/default.conf .config

      - name: Build installer
        run: |
          ninja installer

      - name: Upload installer artifacts
        uses: actions/upload-artifact@v4
        with:
          name: LeonOS-Installer
          path: |
            build/images/leonos4-installer.iso
          if-no-files-found: error
          compression-level: 0